# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f9519240f1981e13244f284c6b1737ef"
name = "Ebook Management"
handle = "ebook-management"
application_url = "https://asks-vulnerable-lucy-alleged.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://ebook-management-app.vercel.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ebook-management-app.vercel.app/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,read_customers,read_orders,unauthenticated_read_customers,write_products"

[auth]
redirect_urls = ["https://asks-vulnerable-lucy-alleged.trycloudflare.com/auth/callback", "https://asks-vulnerable-lucy-alleged.trycloudflare.com/auth/shopify/callback", "https://asks-vulnerable-lucy-alleged.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
